### ISSUE TITLE
Wrong timeout when using 1.0.0-beta.1

### ISSUE THREAD

**Issue by serut** [zinserjan/mocha-webpack#108]
Hello @zinserjan 

I tried your last version of mocha-webpack and I can't run my test in watch mode.

```
mocha-webpack --webpack-config webpack.test.config.js "web_modules/**/*.test.js{,x}" --recursive --require source-map-support/register --inline-diffs --watch
[..]
  12 passing (2s)
  1 failing
[..]
     Error: Timeout of 1ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

When I run not in watch mode, everything works as previously.

```
mocha-webpack --webpack-config webpack.test.config.js \"**/@(tests|web_modules)/**/*.test.js{,x}\" --recursive --require source-map-support/register --inline-diffs
[..]
  185 passing (397ms)
  3 pending
  1 failing
```

**Comment by serut** [comment]
Also there is an issue with that log (`undefined` instead of 0):
```
  186 passing (283ms)
  3 pending
 MOCHA  Tests completed with undefined failure(s)
Process finished with exit code 0
```

**Comment by zinserjan** [comment]
> Error: Timeout of 1ms exceeded. For async tests and hooks, ensure "done()" is called; 

Are you using webpack@1?
When yes, do you see `Tests aborted` in your logs?

I'm asking only because webpack@1 uses a legacy version of it's internal watching library (watchpack). The change detection isn't reliable and triggers often rebuilds even if nothing changed. That's maybe the case here.

I created some days ago a PR to update watchpack in webpack/webpack#3797.

You can try my PR branch in your project with

```bash
$ npm install zinserjan/webpack#webpack-1
```

or add it to your package.json

```json
  "webpack": "zinserjan/webpack#webpack-1"
```




> MOCHA  Tests completed with undefined failure(s)

That's definitly a bug.

**Comment by serut** [comment]
> Are you using webpack@1?
Yeap ! I will try to upgrade webpack but I don't think it will be easy

**Comment by zinserjan** [comment]
Just try my branch, should be easy without any changes. Forgot to say, that the PR is for webpack@1

**Comment by serut** [comment]
`npm install zinserjan/webpack#webpack-1 --save-dev` is not working. Are you sure your package is correclty setup on npm servers ?
Never had such issue before...

**Comment by serut** [comment]
Ok this works: 
`npm install --save-dev https://github.com/zinserjan/webpack/tarball/webpack-1`

**Comment by serut** [comment]
Still some ` MOCHA  Tests completed with undefined failure(s)` (! watch) and `Error: Timeout of 1ms exceeded.` (watch)

**Comment by zinserjan** [comment]
`Error: Timeout of 1ms exceeded. For async tests and hooks, ensure "done()" is called; ...` should only occur when you change a file while async tests are running.

**Comment by serut** [comment]
Can I know which file changed and triggered the rebuild ? Maybe I have a webpack `exclude` that is not well configured...

**Comment by serut** [comment]
> Error: Timeout of 1ms exceeded. For async tests and hooks, ensure "done()" is called; ... should only occur when you change a file while async tests are running.

You're totaly right. It looks like it's a way to finish tests fast when there is already a file change and mocha needs to be rerun. 

The only remaining little bug is the `undefined failure` when I run tests not in watch mode

```
  285 passing (6s)
  2 pending

[mochawesome] Report JSON saved to reports/mocha/mochawesome.json

[mochawesome] Report HTML saved to reports/mocha/mochawesome.html

 MOCHA  Tests completed with undefined failure(s)
```
