### ISSUE TITLE
Using with CoffeeScript

### ISSUE THREAD

**Issue by jensljungblad** [zinserjan/mocha-webpack#114]
I have a file containing CS called `test/test.coffee`

When passing this to mocha-webpack with `mocha-webpack --webpack-config config.js test/test.coffee` the file seems to compile fine using webpack and ends up in `.tmp/mocha-webpack` but it keeps the `.coffee` file extension, even though it contains js. 

The whole thing crashes with `Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee files.`, I assume because it is trying to require a file with a `.coffee` extension.

**Comment by azhang** [comment]
mocha-webpack --require coffee-script/register --webpack-config config.js test/test.coffee

**Comment by zinserjan** [comment]
The entry handling was completely refactored for 1.0.0 and this issue does no longer occur. You can give it a with v1.0.0-beta.1
