### ISSUE TITLE
WebStorm IDE Instructions Not Working - Incorrect relative path prefix inserted in front of absolute paths causing Exit Code 1

### ISSUE THREAD

**Issue by n8sabes** [zinserjan/mocha-webpack#115]
[IDE Instructions](http://zinserjan.github.io/mocha-webpack/docs/guides/ide-integration.html) for WebStorm 2017 do not seem to work, or I am configuring something incorrectly.

I have both VS Code, and npm command line working fine in bash shell, but need WebStorm due to better (live) debugger integration that currently possible in VS Code.

When running a debug session in WebStorm, it appears mocha-webpack is prefixing a relative path (`./../../..`) in front of absolute paths when trying to import modules.

ERROR OUTPUT:
```
WEBPACK  Compiling...

WEBPACK  Failed to compile with 1 error(s)

Error in ./~/mocha-webpack/lib/entry.js

Module not found: './../../../Users/n8/dev/project_workspace/test/model-tests/Widgets.test.ts' in '/Users/n8/dev/project_workspace/node_modules/mocha-webpack/lib'


Process finished with exit code 1
```

**Comment by zinserjan** [comment]
I can reproduce this, so your config should be ok.

Seems like `loaderUtils.stringifiyRequest` transforms the path wrong in https://github.com/zinserjan/mocha-webpack/blob/8f474868deb1924275bc5450a4ef123d7a025341/src/webpack/loader/entryLoader.js#L40

**Comment by n8sabes** [comment]
Glad you were able to reproduce it. Any suggested workarounds, or a fix anytime soon?

Using debugger statements in VS Code is seriously time consuming (e.g. inject debugger statement, re-run test which rebuilds everything, terminate, repeat...), whereas Webstorm breakpoints are much more efficient (especially in promise completion contexts), but now Webstorm isn't working either 😢.

Thanks for any suggestions.

**Comment by eddyerburgh** [comment]
Reverting to 0.x solves this for me

**Comment by pkuczynski** [comment]
@eddyerburgh that's not really a solution, is it? :)

**Comment by pkuczynski** [comment]
My PR #145 fixes the problem!
