### ISSUE TITLE
Allow custom UI options 

### ISSUE THREAD

**Issue by pmoons** [zinserjan/mocha-webpack#117]
`Version 0.7.0`

Hi there,

I really like concept of this project, but when I was setting this package up in my environment, I ran into a little snag.  I use a `bdd-lazy-var` package as a [UI option in mocha](https://github.com/stalniy/bdd-lazy-var#how-to-use) to allow me to define lazy variables. Unfortunately, when I specify the `ui` option as `bdd-lazy-var/rspec`, `mocha-webpack` complains that I didn't pass it a valid option.
```
Argument: ui, Given: "bdd-lazy-var/rspec", Choices: "bdd", "tdd", "exports", "qunit"
```

Seems like these values are checked against [here](https://github.com/zinserjan/mocha-webpack/blob/02b1abe071a19a07366d492a8f9fe6a4caa47cb4/src/cli/parseArgv.js#L123). Is there any workaround I could do to bypass this issue?

**Comment by zinserjan** [comment]
I didn't know that it's possible to add a custom UI. 

There isn't any workaround you can do. We need to remove the choices and add the same path resolution logic like for [reporters](https://github.com/zinserjan/mocha-webpack/blob/master/src/runner/loadReporter.js)

**Comment by pmoons** [comment]
I see the commit you referenced in this issue.  Thanks for the work you are doing.
