### ISSUE TITLE
global beforeEach/afterEach hooks not running in --watch mode

### ISSUE THREAD

**Issue by jknight12882** [zinserjan/mocha-webpack#118]
This is using `1.0.0-beta1`

We have some `beforeEach()/afterEach()` hooks set up at the global level that run before every test. When running without the `--watch` option, and the first time the whole suite runs with `--watch`, these are being executed appropriately. 

However, in `--watch` mode, after a file change, these global hooks are NOT being run, and the tests that rely on them are failing

**Comment by zinserjan** [comment]
Yep, that's correct and works as expected as only changed files or files that were affected by a change are retested.

Every test file should run in isolation, everything else is a bad pattern in my opinion. Normally I never develop against the whole test suite and just use a single test file or directory as entry to have faster compile and test times.

As a workaround you can use `--include` option and pass your file to it. Then it will be run with every file change like described in http://zinserjan.github.io/mocha-webpack/docs/installation/cli-usage.html#-require-include
