### ISSUE TITLE
need a way to set the tmp dir. 

### ISSUE THREAD

**Issue by bcowgill** [zinserjan/mocha-webpack#12]
I needed to move the .tmp dir somewhere else so I 
ln -s /tmp .tmp

and tried to run but got

ERROR in /tmp/mocha-webpack/3b4322aaa3a221e1139cdef1c99b0e0c-entry.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../src in /tmp/mocha-webpack
resolve file
resolve directory
  /src doesn't exist
 @ /tmp/mocha-webpack/3b4322aaa3a221e1139cdef1c99b0e0c-entry.js 5:23-58

    // This gets replaced by webpack with the updated files on rebuild
    var __webpackManifest__ = [];

    var testsContext = require.context("../../src", false);

**Comment by zinserjan** [comment]
Sorry, don't want to provide an option to set the tmp dir. The temp dir is a workaround until i find a way to eliminate it.

Anyway, the paths with a leading / looks strange. Are you calling mocha-webpack from your root directory? Normally your project path should appear in the file paths.

**Comment by zinserjan** [comment]
Closing this in favour of #25.
