### ISSUE TITLE
Support for multiple reporters

### ISSUE THREAD

**Issue by benhughes** [zinserjan/mocha-webpack#120]
If I run mocha-webpack with two reporters ` --reporter mocha-junit-reporter --reporter spec` I get 
```
Error: Duplicating arguments for "--reporter" is not allowed. "--reporter mocha-junit-reporter --reporter spec" was provided, but expected "--reporter mocha-junit-reporter"
```

seems an overlooked feature as I need to be able to run mocha-junit-reporter and also use the basic spec reporter otherwise I'm not told what test has failed in the command line output.

**Comment by zinserjan** [comment]
Mocha doesn't support multi reporters, but there is an open PR for that https://github.com/mochajs/mocha/pull/2184.

Can you try to use a workaround until this as merged like [mocha-multi](https://github.com/glenjamin/mocha-multi) or something similiar?

**Comment by benhughes** [comment]
OK I'll close this then as it's not an issue with mocha webpack. Thanks
