### ISSUE TITLE
Cannot read property getFiles of undefined 1.0.0.beta.0/1

### ISSUE THREAD

**Issue by jamespedid** [zinserjan/mocha-webpack#127]
#125 
Hello; I'm trying to run mocha-webpack on 1.0.0.beta.0, and it seems that the webpack build process is failing with the following message:

```
 WEBPACK  Failed to compile with 1 error(s)

Error in ./~/mocha-webpack/lib/entry.js

   TypeError: Cannot read property 'getFiles' of undefined
```

Tracking it down, it seems like you're calling a getFiles on some config object, but it's not clear to me how this object should be provided, and it's preventing the tests from running. Any suggestions on how to fix this?

Thanks!

EDIT: I tracked it down to be a problem with the webpack.config.test.js file that I have. Maybe this can be detected and thrown an error if something here is wrong.

**Comment by realseanp** [comment]
So what was the fix ? @jamespedid

**Comment by jamespedid** [comment]
Unfortunately I ended up abandoning mocha-webpack for the time being, however it wasn't the issue because I manually recreated the issue in a different way and found out some configuration issues. However, the way I'm running it now is much faster than mocha-webpack at runtime, especially with JSDOM tests.

We also found it useful to simply use null-loaders for things like CSS and such to load these kinds of files, which was an improvement. Lastly, there was a few odd whitelists that we had to do with nodeExternals to make things work properly with how we were using things.

Here's a few things that I found relevant:

1. Use a test-context file as your entry point. That is, I found a snippet below that seems to work wonders:

```javascript
const context = require.context(__dirname, true, /\.test\.js/);
context.keys().forEach(context);
module.exports = context;
```

For running the tests with parameters, we ended up using a bash script that looks sort of like this. We always output to the same test-bundle.js file and ran it with mocha. We used the source-map-support/register directly when using mocha.

```bash
#!/bin/bash -ex

if [[ $1 ]]; then
    webpack --progress --colors --config webpack.config.test.js $1 && mocha --colors --require source-map-support/register .tmp/test-bundle.js
else
    webpack --progress --colors --config webpack.config.test.js test/test-context.js && mocha --colors --require source-map-support/register .tmp/test-bundle.js
fi
```

The test execution time for ~700 tests dropped from to 3s from a much more significant chunk of time. I'm can't recall what was the biggest contributing factor, but something in our combination didn't work well with mocha-webpack

**Comment by barnabaskecskes** [comment]
I'm having the same issue when trying to hook this into Laravel Mix (even with a fresh Laravel 5.5 install). I have posted a comment there but was advised to post it here instead (see post below from the Laracasts website). I know this is still in beta so hoping that this can be fixed asap. (`v0.7` works just fine with the same setup so it is assumed the new version is at fault..)

![screen shot 2017-10-28 at 09 02 44](https://user-images.githubusercontent.com/3535449/32132636-2a74ca1e-bbbf-11e7-9f8e-afb8e1a19b5e.png)

**Comment by zinserjan** [comment]
@barnabaskecskes can you create a repo to reproduce this?

**Comment by barnabaskecskes** [comment]
@zinserjan [here you are](https://github.com/barnabaskecskes/mocha-webpack-test)

**Comment by fshequin** [comment]
I have the same problem as @barnabaskecskes

**Comment by barnabaskecskes** [comment]
Would be handy if @zinserjan could fix this as I'm having #45 error now, which has been implemented in the beta version that currently fails for us. :)

**Comment by zinserjan** [comment]
Should be fixed with 1.0.1

**Comment by barnabaskecskes** [comment]
@zinserjan @fshequin Indeed it is fixed now. Thanks a ton!

![screen shot 2017-10-28 at 21 26 17](https://user-images.githubusercontent.com/3535449/32138226-dc2c3f0a-bc26-11e7-8189-12729ef50f33.png)

**Comment by fshequin** [comment]
Also fixed for me now too, that was fast for a weekend.....thank you @zinserjan
