### ISSUE TITLE
Mocha-webpack + eslint

### ISSUE THREAD

**Issue by Snowshield** [zinserjan/mocha-webpack#128]
I trying to use mocha-webpack + eslint to lint my test.

My webpack config file. I use sslint loader with enforce: "pre" option because i want to run linting before tests. Also i use NoEmitOnErrorsPlugin to dont run test if any lint error occur.

```
const webpack = require('webpack');
const NODE_ENV = process.env.NODE_ENV || 'production';
const DEVELOPMENT = NODE_ENV === "development";

module.exports = {
  target: 'node',
  bail: true,
  watch: DEVELOPMENT,
  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.(js)$/,
        loader: "eslint-loader",
        include: /test/,
        enforce: "pre",
        options: {
          formatter: require("eslint-friendly-formatter"),
          cache: DEVELOPMENT
        }
      },
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: /test/,
      }
    ],
    noParse: /.*(\\|\/)dist(\\|\/).*/
  }
};
```
When i run my bad-code-styled tests i see all linter warnings but testing still proceed and i see shows its result in console.
So is there way to use eslint before testing with mocha-webpack?

**Comment by serut** [comment]
I do not recommend the eslint + webpack technic because I usually do this "workflow" :

- save my file a first time
- see that I forgot something and I add it
- save again

==> My IDE ask me why the file on the disk, linted my eslint in a background task, have been edited.since the last edition.

**Comment by zinserjan** [comment]
> When i run my bad-code-styled tests i see all linter warnings but testing still proceed and i see shows its result in console.
So is there way to use eslint before testing with mocha-webpack?

eslint-loader needs to emit errors instead of warnings to keep mocha-webpack from testing. see https://github.com/MoOx/eslint-loader#emiterror-default-false
