### ISSUE TITLE
Multiple entries

### ISSUE THREAD

**Issue by davidhantson** [zinserjan/mocha-webpack#134]
With normal mocha you can specify something like this:

> mocha ./test/setup.js ./test/**/*.spec.js

It will first execute the first file then hop on to the next space separated glob pattern. This is needed when setting your config json file on the global object first before running all files. 

webpack-mocha only allows 1 entry and my setup breaks. Now I have to go everywhere and import the config everywhere instead of using the global object. This restricts a lot of possibilities on the next environments.

**Comment by zinserjan** [comment]
Multiple entries works with 1.0.0 (see #70)
