### ISSUE TITLE
Failing on flow tokens and webpack aliases

### ISSUE THREAD

**Issue by leighman** [zinserjan/mocha-webpack#138]
I'm trying to use mocha-webpack to do unit testing in a vue application as discussed in [this blog post](https://www.coding123.org/unit-test-vue-components-beginners/)

In package.json:
`mocha webpack --webpack-config build/webpack.base.config.js \"src/**/*.spec.js\"`

My test file uses the alias '@' for the src directory and the file it imports uses flow type checking.
Mocha-webpack seems to choke on one/both of these things.

webpack.base.config is from the [vue-cli template] (https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js)

babel is using the "syntax-flow" and "transform-flow-strip-types" plugins and mocha-webpack should be passing the js files through babel-loader files, right?

Is this a bug or am I being stupid?
Thanks.

**Comment by zinserjan** [comment]
Can you make sure that mocha-webpack loads your webpack-config? Maybe add some logs into your config.

At the moment mocha-webpack does not throw any errors when the config is missing (see #126).

**Comment by leighman** [comment]
Haha. That was it. Among other things. Thanks.
