### ISSUE TITLE
Run into several issues

### ISSUE THREAD

**Issue by SirCmpwn** [zinserjan/mocha-webpack#14]
Hi there. I've got this software more or less working but I've hit a few issues. My repository is here:

https://github.com/Linode/manager

I'm having two main issues:
1. I can't figure out how to get source maps working, so errors during tests don't have meaningful stack traces
2. I can't figure out how to import the rest of the code. Doing it in test/setup.js causes errors with jsdom's window not being available and there's no other clear place where it's appropriate to make sure everything gets imported - which will be useful when I try to add code coverage to the mix later.

**Comment by damonsmith** [comment]
I'm going to break out the sourcemap issue into it's own issue.

**Comment by zinserjan** [comment]
- sourcemap works out of the box (#82)
- importing the rest of the code is possible (#79)

Both will be available with v1.0.0.
