### ISSUE TITLE
update peerDependencies and devDependencies to support webpack 3.0.0

### ISSUE THREAD

**Issue by paztis** [zinserjan/mocha-webpack#144]
Hi,

Is it possible to update peerDependencies and devDependencies to support webpack 3.0.0 ?
It will avoid warnings during npm install.

Thanks

**Comment by serut** [comment]
Yup, it's working fine with webpack 3. 

`1.0.0-beta.1` is quite stable and can be released as a stable version, even if the `watch` functionnality can be improved.

Also, we're releasing our big project that uses `mocha-webpack` in few days.

**Comment by paztis** [comment]
HI,
Can you also publish your new version because without it, warning will stay displayed ^^

**Comment by zinserjan** [comment]
#139 and #115 needs to be fixed before
