### ISSUE TITLE
publish npm

### ISSUE THREAD

**Issue by azhang** [zinserjan/mocha-webpack#157]
Can we get this published in a new version on npm? I'd like to start using the changes from my merged PR but linking directly to this repo doesn't work due to the build process.

Thanks!

**Comment by zinserjan** [comment]
Yep, my plan is to publish a RC for 1.0.0 when #154 & #145 is solved and a week later 1.0.0.

**Comment by zinserjan** [comment]
Done in https://github.com/zinserjan/mocha-webpack/commit/fd0b032d3a6f6c78d1240131c00109b8e1232709
