### ISSUE TITLE
DeprecationWarnings with Webpack 3

### ISSUE THREAD

**Issue by matt-d-rat** [zinserjan/mocha-webpack#158]
- __mocha-webpack:__ v1.0.0-beta.1
- __webpack:__ v3.1.0
- __mocha:__ v3.4.2
- __Node:__ v6.11.0

__Expected Outcome:__

When running the unit tests, only the test results should be displayed.

__Actual Outcome:__

When running the tests the following deprecation warnings are output to the terminal along with the test results:

```sh
(node:28348) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
(node:28348) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
```

As per the warning, these functions have been deprecated in Webpack 3 and should be replaced with the functions suggested by the warning.

These warnings do not impact the test results nor do they effect the functionality of mocha-webpack, they are just a bit unsightly.

**Comment by matt-d-rat** [comment]
- https://github.com/zinserjan/mocha-webpack/blob/master/src/webpack/util/getAffectedModuleIds.js#L87
- https://github.com/zinserjan/mocha-webpack/blob/master/src/webpack/util/getBuildStats.js#L35

Appear to be the culprits.

**Comment by hugoduraes** [comment]
I'm also getting these deprecation warnings.

**Comment by zinserjan** [comment]
Thanks for reporting and the good analysis. Awesome!
