### ISSUE TITLE
babel polyfill is instantiated twice in watch mode, which results an error

### ISSUE THREAD

**Issue by fehergeri13** [zinserjan/mocha-webpack#168]
Either I include the babel polyfill in the `--require helper.js` or include with `--include babel-polyfill`, when I change a file in watch mode, the tests fails 

```
"test": "mocha-webpack --include babel-polyfill test/**/*.test.js --webpack-config webpack.config.js --require ./test/helpers.js --recursive --watch",
```
I start the script, all test passing, and then I change a file, for example add a new line, and then I get this error:

```
RUNTIME EXCEPTION  Exception occurred while loading your tests
Error: only one instance of babel-polyfill is allowed
```

**Comment by zinserjan** [comment]
Use `--require`
