### ISSUE TITLE
Libs providing ES2015-native imports are not processed correctly

### ISSUE THREAD

**Issue by DorianGrey** [zinserjan/mocha-webpack#169]
Hey there,

I'm currently evaluating different test-runners for being viable to replace the current karma + phantomjs + jasmine based setup in my [angular-template](https://github.com/DorianGrey/ng-webpack-template) (and maybe other projects).
The project is using [lodash-es](https://github.com/lodash/lodash/tree/es), which uses ES2015 import/export and thus provides better tree-shaking abilities than its basic version. Regularly, this is not a problem, since webpack should deal with these - and it does with the current setup, in test, dev and production mode.

However, using `mocha-webpack`, it does not seem to do so:
```
 WEBPACK  Compiled successfully in 5331ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

/home/linne/Projects/ng-webpack-template/node_modules/lodash-es/assign.js:1
(function (exports, require, module, __filename, __dirname) { import assignValue from './_assignValue.js';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/home/linne/Projects/ng-webpack-template/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
```
I've created a branch that illustrates this issue: https://github.com/DorianGrey/ng-webpack-template/tree/mocha-test
Had a similar problem when evaluating `jest` (see [here](https://github.com/DorianGrey/ng-webpack-template/tree/jest-test)), which got fixed by transforming the module using `babel`. I've tried the same approach in this case using `babel-loader` and the corresponding `transform-es2015-modules-commonjs` plugin, but that seemed to have no effect. Also tried to add a `resolve.alias` to the test config to let the references to `lodash-es/*` point to different implementations (using commonjs), but it seems that these config entries got ignored completely. Attempted to find projects that already mastered this setup and found [this](https://github.com/HichamBI/Angular-testing-webpack-mocha-chai-sinon) - however, it failed with the same error when I added `lodash-es`.

I.e.: It either seems that the bundling process has some differences from webpack's defaults, or I've overlooked something.

Execution environment:
- node 6.11.1
- Ubuntu 16.04

**Comment by shamansir** [comment]
For mocha, I used `mocha --compilers js:babel-core/register ...` option, but `mocha-webpack` is not supporting it.

**Comment by zinserjan** [comment]
Node doesn't support es6 modules and with the node-externals-plugin transpiling of all node_modules is skipped.

There are 2 solutions:
- whitelist lodash-es
- register babel-register with `--require`, but note that babel skips node_modules also by default

**Comment by DorianGrey** [comment]
Hm... now that you mention it, I recognize that I've overlooked the config options of [webpack-node-externals](https://github.com/liady/webpack-node-externals).
Works using 
```
externals: [
    nodeExternals({
      whitelist: [/lodash-es/]
    })
  ]
```
- at least for what this tool is responsible for (still some caveats with mocha, chai and sinon).

Thanks for the hint!
