### ISSUE TITLE
mocha required file does not run through webpack

### ISSUE THREAD

**Issue by Bamieh** [zinserjan/mocha-webpack#174]
When adding `--require file.js` the file.js does not run through webpack. This causes the code to be split between normal code and webpack code.

```
--require config/index.js
```

For example i have some plugins like `dotEnv` and `DefinePlugin` that i use inside my test cases, but i do not have access to inside the setup file, because the required file does not run through webpack. Am i missing something or it is indeed not supported? if not, i am willing to submit a pull request if you see what i'm talking about is sensible enough.

I do know that using include will pass the file through webpack, however, it runs on each watch iteration, so it is not convenient and some setup files throw errors if called more than once, etc.

**Comment by zinserjan** [comment]
Yep, that's intended. use `--include` instead.
