### ISSUE TITLE
1.0.0-rc.1: not implicitly picking up webpack.config.js

### ISSUE THREAD

**Issue by yyx990803** [zinserjan/mocha-webpack#178]
The docs states that:

> When the parameter --webpack-config is omitted, mocha-webpack tries to load a webpack-config file named webpack.config.js, but will not bail when it doesn't exist.

However with a `webpack.config.js` in cwd, it seems to be ignored unless explicitly specified with `--webpack-config webpack.config.js`.

BTW: great work on the project, we are recommending this in Vue.js' official testing guide, would love to help in anyway we can.

Update: [repro](https://github.com/yyx990803/mocha-webpack-repro)

**Comment by zinserjan** [comment]
Thanks for reporting. Found the issue, default value for webpack config is wrong. 

It's named [webpack-config.js](https://github.com/zinserjan/mocha-webpack/blob/e7d0f061dd16d665e2db41a8895852e2cf4c4600/src/cli/parseArgv.js#L174) instead of `webpack.config.js` :hushed:

**Comment by yyx990803** [comment]
Oh haha that's totally my fault, thanks!

**Comment by zinserjan** [comment]
I fixed the config name in #186. `webpack.config.js` makes more sense cause it's already documented and it's also the default of webpack.
