### ISSUE TITLE
Support Mocha 4.x?

### ISSUE THREAD

**Issue by keirlawson** [zinserjan/mocha-webpack#182]
Would be great to be able to use the latest version of Mocha with this.

**Comment by FallingSnow** [comment]
I'm using Mocha 4.0.1 and everything is working fine.

**Comment by keirlawson** [comment]
Great! I guess its just the peer dependencies and docs that would need updated then?

**Comment by modosc** [comment]
see #179

**Comment by zinserjan** [comment]
released with 1.0.0
