### ISSUE TITLE
Path resolution partially broken, if using absolute path or a relative one with one dot

### ISSUE THREAD

**Issue by octaharon** [zinserjan/mocha-webpack#183]
`~# mocha-webpack "tests/api/**/*.js"` works fine, if run from proper folder. Obviously breaks if run from another one, that behaves as expected

`~# mocha-webpack "./tests/api/**/*.js"` doesn't pick up any files (the result is "0 passing"), though the path is resolved correctly, generated "-entry" files are the same, but the build output doesn't contain any of the tests files compiled

the same with absolute path glob, like '/var/www/tests/api/**/*.js'

Meanwhile it resolves properly if run from another folder, like
`~/src# mocha-webpack "../tests/api/**/*.js"` - works fine

I don't know the considerations behind this, but according to general CLI usage experience it should work all the same. Also note that paths for --webpack-config and --opts are resolved correctly, for instance

**Comment by zinserjan** [comment]
Can you log `this.entries` [here](https://github.com/zinserjan/mocha-webpack/blob/fd26d2104f6b48c6351b05358c456c1ede5f1c0a/src/runner/TestRunner.js#L241) and also log resolved `files` and `entryConfig.getFiles()`?

There must be something wrong there.
