### ISSUE TITLE
Cant resolve webpack Aliases with mocha

### ISSUE THREAD

**Issue by BbosaH** [zinserjan/mocha-webpack#185]
Now the big problem is that i cant resolve webpack aliases with mocha or mocha webpack. 
I have aliases of this sort in my webpack 

```
alias: {
       LoginActions : path.resolve(__dirname, 'app/actions/login-actions.jsx/'),
}
```
in my components which are not tests i import it like this

`import LoginActions from 'LoginActions'`

this is fine .. but the problem comes when i run tests on these modules .  My test case is here.

```
import {assert} from "chai";
 import {emailChangeAction,loginAction} from "LoginActions";

 describe("LoginActions",()=>{
    describe('changeEmailAction',()=>{
      it('Should generate changemail Action',()=>{
          const action ={
            type :'EMAIL_CHANGED',
            email:'bbosa.henry1@gmail.com'
          }
          const res = emailChangeAction(action.email);
          assert.equal(res,action);


      })

    });

 });
```

in my console i get this error 
`Module not found: 'LoginActions' in 'C:\projects\aurity\reactweb\test\actions'`

in my package.json i have this script:

```
scripts :{
     "test": "mocha-webpack  --recursive \"test/**/*.@(js|jsx)\"",
}
```

Now how do i test with with these aliases. Because i use them alot in my project

**Comment by zinserjan** [comment]
Can you try to pass the webpack config explicitly via the parameter `--webpack-config`? 
Probably the same issue like #178

**Comment by BbosaH** [comment]
I did that. I get some error  below 
```
Missing argument value: webpack-config
npm ERR! Test failed.  See above for more details.
```

**Comment by BbosaH** [comment]
Ii finally worked with this script
scripts :{
    "test": "mocha-webpack --webpack-config webpack.config.js --recursive \"test/**/*.@(js|jsx)\"",
}
