### ISSUE TITLE
[Feature Request] Provide an option to not clear the terminal automatically

### ISSUE THREAD

**Issue by matt-d-rat** [zinserjan/mocha-webpack#194]
I really like that the terminal automatically clears on test re-runs, however I was wondering whether we could get an option to disable this behaviour?

My use case is for CI build environments (such as Travis CI) - where the other pertinent information about the build gets cleared once the unit tests commence.

This would be extremely helpful.

**Comment by peterjwest** [comment]
I would like to upgrade this to please *don't* clear the terminal automatically, why would anyone want this? It wipes my entire terminal history every time I run it.

**Comment by peterjwest** [comment]
You can use the command line option `--interactive false` to prevent this. I'm not sure what else this changes, but it works!

**Comment by matt-d-rat** [comment]
@peterjwest Ah that's good to know, I must of missed that in the documentation. I'll close this issue as that is the answer I was looking for.
