### ISSUE TITLE
--watch crashing on errors

### ISSUE THREAD

**Issue by kendagriff** [zinserjan/mocha-webpack#20]
Thanks for a great tool – excited to be able to hot-reload my test code.

Any insights on how to prevent `--watch` from crashing, and exiting, when errors are introduced into a test file? Do I have a configuration option set incorrectly in webpack?

**Comment by zinserjan** [comment]
Hmm, that shouldn't happen. 

Can you provide me a repo?

**Comment by kendagriff** [comment]
You bet... I'll have one soon...

**Comment by kendagriff** [comment]
K, I wouldn't be surprised at all if I've set something up incorrectly, but here's a very simple reproduction:

[demo-mocha-webpack-crash](https://github.com/banzai-inc/demo-mocha-webpack-crash)

**Comment by zinserjan** [comment]
Thanks! Fixed with #21

**Comment by kendagriff** [comment]
Excellent, do you plan to cut a new release?

**Comment by zinserjan** [comment]
Yep, release is planned for this evening.

**Comment by zinserjan** [comment]
Released with v0.4.0
