### ISSUE TITLE
Not running tests or am I missing something?

### ISSUE THREAD

**Issue by ViggoV** [zinserjan/mocha-webpack#219]
Hi. I am desperately trying to get webpack-mocha to run in my existing webpack project. Thus far I can get it to compile, but no tests are run. I have a `webpack.config.test.js` in the root of my project which looks like this:
```javascript
'use strict';

require('webpack');
var nodeExternals = require('webpack-node-externals');

var config = {
  target: 'node', // webpack should compile node compatible code
  mode: 'development',
  externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
};

module.exports = config;
```

and a sample test located in `test/testtest.test.js`, which looks like this:
```javascript
var assert = require('chai').assert;

desribe('Array', function() {
  describe('#indexOf', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal(-1, [1,2,3].indexOf(4));
    });
  });
});
```

Finally I have my `package.json` with the following:
```json
"scripts": {
  "test": "mocha-webpack --webpack-config webpack.test.config.js --glob \"*.test.js\" --recursive"
}
```

The ouput of `npm run test`, however, only gives me the following:
<img width="457" alt="skaermbillede 2018-03-20 kl 13 34 34" src="https://user-images.githubusercontent.com/3153568/37654823-b34bdb3a-2c43-11e8-9784-c5ce32c18f5d.png">

**Comment by laem** [comment]
This may happen if you're using Webpack 4, see #220 .

**Comment by ViggoV** [comment]
That would make sense. Thank you. I'll be looking forward to the release

**Comment by ViggoV** [comment]
It seems you were right. Downgrading to Webpack 3.11.0 solved it.

**Comment by adonespitogo** [comment]
Definitely caused by webpack 4. Support for webpack 4 is currently on master branch and not released yet. Perhaps this issue can be closed.

**Comment by ViggoV** [comment]
Closing

**Comment by davidyell** [comment]
I'm experiencing this issue.
