### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by rgeddes** [zinserjan/mocha-webpack#228]
Ubuntu 16.04 / nvm / node 8.10.0

After installation, mocha-webpack throws "Permission Denied" error when running as npm script.  

I'd like to know I won't run into problems if I follow this pattern, or better yet, that this issue gets resolved.

TLDR:
Tried a few things, the only way I could get this to work:

from the project root directory
`ln -s ./node_modules/mocha-webpack/bin/mocha-webpack .`

and changed the npm test script to:
`"test": "node mocha-webpack \"test/test.js\""`

---------------

The following is a log of what I did.

Install instructions at https://github.com/zinserjan/mocha-webpack/blob/master/docs/installation/setup.md .

Check the packages:
```
npm ls -s --depth=0
├── mocha@5.0.5
├── mocha-webpack@1.1.0
└── UNMET PEER DEPENDENCY webpack@4.3.0
```
Check version
```
$> node node_modules/mocha-webpack/bin/mocha-webpack --version
1.1.0

```
Run a test file that should have 2 passing tests
```
$> node node_modules/mocha-webpack/bin/mocha-webpack test/test.js
 WEBPACK  Compiled with 1 warning(s)

Warning 

  configuration
  The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.
```
Suspect the UNMET PEER DEPENDENCY on webpack and downgrade webpack
```
$> npm ls -s --depth=0
├── mocha@5.0.5
├── mocha-webpack@1.1.0
└── webpack@3.11.0
```

Run sample test again
```
$> node node_modules/mocha-webpack/bin/mocha-webpack test/test.js
 WEBPACK  Compiled successfully in 125ms

 MOCHA  Testing...

  Array
    #indexOf()
      ✓ should return -1 when the value is not present
      ✓ should return the index of the value when the value is present

  2 passing (3ms)

 MOCHA  Tests completed successfully
```
Modify test script in package.json:
`"test": "mocha-webpack \"test/test.js\""`

Run the test from npm:
```
$> npm run test
> mocha-webpack "test/test.js"

sh: 1: mocha-webpack: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! mocha_demo@1.0.0 test: `mocha-webpack "test/test.js"`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the mocha_demo@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rgeddes/.npm/_logs/2018-03-28T20_42_01_871Z-debug.log
```
Tried a few things, the only way I could get this to work:

from the project root directory
`ln -s ./node_modules/mocha-webpack/bin/mocha-webpack .`

and changed the npm test script to:
`"test": "node mocha-webpack \"test/test.js\""`

**Comment by zinserjan** [comment]
This looks like an issue with your npm setup. As the error says your user have no access rights to run the scripts. I guess that you installed with sudo rights which leads to this error.

Anyway closing this cause it's not a mocha-webpack issue.

**Comment by rgeddes** [comment]
My setup is with nvm, so node/npm ( including my global package repo ) are installed in my home directory with me as as the owner.  So, I don't think it's a permissions issue.
