### ISSUE TITLE
 --compilers js:babel-core/register cause argv parse error

### ISSUE THREAD

**Issue by neekey** [zinserjan/mocha-webpack#23]
I found adding option `--compilers js:babel-core/register` causes mocha-webpack always return help output, like:

```
$ ./node_modules/mocha-webpack/bin/mocha-webpack -R spec --require test/setup.js --compilers js:babel-core/register --webpack-config ./test/webpack.config.test.js ./test/index.js
Advanced options:
  --async-only, -A  force all tests to take a callback (async) or return a
                    promise                                            [boolean]
  --recursive       include sub directories                            [boolean]
  --bail, -b        bail after first test failure     [boolean] [default: false]
  --glob            only run files matching <pattern> (only valid for directory
                    entry)                                              [string]
  --grep, -g        only run tests matching <pattern>                   [string]
  --fgrep, -f       only run tests containing <string>                  [string]
  --invert, -i      inverts --grep and --fgrep matches[boolean] [default: false]
  --require, -r     require the given module                            [string]
  --include         include the given module into test bundle           [string]
  --slow, -s        "slow" test threshold in milliseconds       [default: 75 ms]
  --timeout, -t     set testneekeydeMBP:react-webpack-spa neekey$ 
```

**Comment by zinserjan** [comment]
Yep, that's because `--compilers` is an invalid option for mocha-webpack. There's no need for this option because webpack already have [loaders](https://webpack.github.io/docs/loaders.html).

For your use case, please have a look at [babel-loader] (https://github.com/babel/babel-loader).

**Comment by neekey** [comment]
that makes sense, i actually just copied my mocha configs to mocha-webpack,
it really took me a long time to figure out this problem, i think it will
be better to throw an error to indicate that : )

On Monday, 27 June 2016, Jan-André Zinser <notifications@github.com> wrote:

> Yep, that's because --compilers is an invalid option for mocha-webpack.
> There's no need for this option because webpack already have loaders
> <https://webpack.github.io/docs/loaders.html>.
>
> For your use case, please have a look at babel-loader
> <https://github.com/babel/babel-loader>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zinserjan/mocha-webpack/issues/23#issuecomment-228681629>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAegnq2u8WvR5TSzw7Iknz0w4rGa6bFkks5qP4dEgaJpZM4I-1zR>
> .
>


-- 
发自移动版 Gmail
