### ISSUE TITLE
Mocha is not testing

### ISSUE THREAD

**Issue by WhoAmIRUS** [zinserjan/mocha-webpack#233]
Writing that compiled successfully  but not testing
![1](https://user-images.githubusercontent.com/29947304/38192627-65097706-3676-11e8-9886-32015af2e15d.PNG)

I don't understand what is works with wrongs

package.json:
`"test": "mocha-webpack --webpack-config webpack.config-test.js \"./src/**/**/*.test.js\""`

webpack.config-test.js:

const nodeExternals = require('webpack-node-externals'); 

module.exports = { 
  mode: 'development', 
  target: 'node', 
  externals: [nodeExternals()], 
};

sum.test.js in _dirname/src/demo-feature/js/sum.test.js:

import { describe, it, context } from 'mocha';
import { expect } from 'chai';
import sum from './sum';

describe('sum', () => {
  context('when both arguments are valid numbers', () => {
    it('adds the numbers together', () => {
      expect(sum(1, 2)).to.equal(3);
    });
  });
});

help please

**Comment by zinserjan** [comment]
Did you use mocha-webpack@next or 1.1.0? 1.1.0 does not work with webpack@4

**Comment by WhoAmIRUS** [comment]
Oh, yea, thank u
