### ISSUE TITLE
Chokidar dependêncies broke npm install

### ISSUE THREAD

**Issue by marcusmourao** [zinserjan/mocha-webpack#239]
Hi everyone, I am using mocha-webpack to run unit testing in my nuxt app. So when i install it, mocha-webpack add chokidar as dependencie. Chokidar needs fsevents (not optional) so its broke my npm install in linux system. What can i do?

**Comment by zinserjan** [comment]
fsevents is a optional dependency, see https://github.com/paulmillr/chokidar/blob/2.0.3/package.json#L44

mocha-webpack is also tests on linux via travis. So something else seems to break your npm install

**Comment by marcusmourao** [comment]
I don't know exactly what cause this, but if i have `mocha-webpack` in devDependencies the problem related occurrs in `npm install --only=production` and works good in `npm install`. My solution was add `mocha-webpack` as project dependencies and it resolves. Thanks for support.
