### ISSUE TITLE
Mocha output style is lost

### ISSUE THREAD

**Issue by neekey** [zinserjan/mocha-webpack#24]
when using mocha-webpack, I found the original mocha test output color is lost:

![image](https://cloud.githubusercontent.com/assets/499870/16372553/89c7da6a-3c90-11e6-8c13-4fe20913b3d3.png)

which should be like below:

![image](https://cloud.githubusercontent.com/assets/499870/16372535/7797ce90-3c90-11e6-91d8-bac6f6f806e4.png)

I know it's not a big deal, but all the passing color just make people happy : )

**Comment by zinserjan** [comment]
Did you try `--colors` or `-c`?

**Comment by neekey** [comment]
@zinserjan Thanks, it works. Why not make it the default behavior like mocha does?

**Comment by zinserjan** [comment]
Fixed with #31 and released as 0.5.0
