### ISSUE TITLE
Write to and read from memory

### ISSUE THREAD

**Issue by wuct** [zinserjan/mocha-webpack#25]
Currently, `mocha-webpack` compile the webpack bundle to `.tmp` folder and let `mocha` read it from there. This process is time-consuming.

I suggest we should write the bundle to memory and let `mocha` read it from memory. [This blog](http://alexfedoseev.com/post/68/test-webpack-specific-builds-with-mocha) shows that it is a feasible way by using an undocumented `mocha` api.

If this looks good to you, I would like to give it a try :)

**Comment by zinserjan** [comment]
Yeah, I like the idea of handling everything in memory. I always wanted to implement this feature, but never found the time.

If you would like to give it a try, please do it. .

We have to consider a few things:
- write bundle to memory
- read bundle from memory
- compatibility with sourcemaps ([node-source-map-support](https://github.com/evanw/node-source-map-support))
- code splitting
- debug support for IDE's (e.g. Webstorm mocha plugin)

**Comment by zinserjan** [comment]
mocha-webpack compiles to memory now (#83)

**Comment by wuct** [comment]
Thanks!
