### ISSUE TITLE
Tests do not run with TypeScript & webpack 4

### ISSUE THREAD

**Issue by fkleuver** [zinserjan/mocha-webpack#252]
I used someone else's repro for a different issue as a basis: https://github.com/jdeanwaite/ts-mocha-webpack-example

This repo works as-is. Webpack reports "successful compilation" and mocha reports the test outputs.

Now upgrade the devDeps to their latest versions:
![image](https://user-images.githubusercontent.com/9655331/39675588-83609598-515d-11e8-812a-25868a546f9c.png)

Webpack will still report "successful compilation" but the tests do not seem to run (or their results are not reported.

**Comment by quaternion** [comment]
try `mocha-webpack@next`

**Comment by fkleuver** [comment]
Ah-ha! Works like a charm, cheers!
