### ISSUE TITLE
Third party reporters not working

### ISSUE THREAD

**Issue by Raykeen** [zinserjan/mocha-webpack#253]
Mocha-webpack crashes with `Error: Cannot find module C:\[project-path]\mocha-teamcity-reporter`. Error occured when overriding reporter with cli `webpack-mocha --mocha.opts --reporter mocha-teamcity-reporter` or defining reporter in opts file. Using reporter with cli and without opts file works well.

**Comment by pavel-flyagin** [comment]
I have the same problem. `webpack-mocha --reporter mocha-teamcity-reporter` is not working, but
if I write `webpack-mocha --reporter node_modules/mocha-teamcity-reporter` all works well. It seems like webpack-mocha forgets to find reporter in node_modules
