### ISSUE TITLE
include babel-polyfill

### ISSUE THREAD

**Issue by arunkjn** [zinserjan/mocha-webpack#26]
Hi,

I need to include babel polyfill to use generator functions inside my generated test code. It is not possible to specify it in the webpack entry since this project overrides the provided entry config. How would you achieve the same here? maybe we can enable it using a command line arg

**Comment by Kovensky** [comment]
you could directly `import 'babel-polyfill'` in any file that might need `babel-polyfill`'s features; the problem is, you _have_ to put it in all files (or in a common dependency of all your tests), otherwise it might not run before your code does.

**Comment by arunkjn** [comment]
thanks for the help. I got around it by using the flag --include \"babel-polyfill\" and not ending up doing it in all my files.

**Comment by Thorarin** [comment]
For people googling this issue:
According to the command line help, mocha-webpack has no --include option, but it seems to be an alias for --require. Either seems to do the trick.
