### ISSUE TITLE
Webpack compiles but mocha isn't executed

### ISSUE THREAD

**Issue by fabiante** [zinserjan/mocha-webpack#260]
Hi,

I have a very simple webpack project. When trying to user mocha-webpack, it does compile bot mocha isn't executed:

![image](https://user-images.githubusercontent.com/7669818/40501300-c31efcdc-5f87-11e8-953e-ffb6bb7e3284.png)

After that there is no mocha execution, even though my test folder contains a simple test:

```js
import { something } from "../src/js/data";
import { assert } from "chai";

it("Assert", () => {
    assert.equal(something, 2); // This should throw
})

it("Test", () => {
    throw "NO";
})
```

But nothing shows on my CLI expect for the message in the screenshot.
I don't know if mocha just isn't called or if somehow mocha-webpack doesn't find my test.

This is the important part of my folder structure:

![image](https://user-images.githubusercontent.com/7669818/40501447-246dbf64-5f88-11e8-8142-98bfc1e13fdb.png)

Sorry if this is a usage error but I couldn't find any solutions.

**Comment by zetaraku** [comment]
I encountered the exactly same problem today.
As mentioned in #209, the problem was fixed recently.
`npm install mocha-webpack@next` should solve your problem.

**Comment by fabiante** [comment]
Well that was easy! Thank you very much!!

**Comment by Fohlen** [comment]
I can report that `mocha@next` works indeed 👍

**Comment by elijah-ezaga** [comment]
I had the same issue yesterday and today. `mocha@next` solved it
