### ISSUE TITLE
Watching files and running test in docker container.

### ISSUE THREAD

**Issue by Blaugold** [zinserjan/mocha-webpack#30]
I would like to run tests inside a docker container and use the watch feature. The source directory is mounted into the container, which is problematic in terms of watching files. The fix is to use polling. With webpack you can use:
 ```
watchOptions: {
    poll: true
}
```
This works well for me when running `webpack -w` but with mocha-webpack test are only rerun sporadically when files change. Taking a quick look at the source it seems like mocha-webpack takes the webpack.config file and uses webpack for watching. So it should work too.

It would be great if I could get this working reliably.

**Comment by zinserjan** [comment]
Support for watchOptions is added with #35 and released as 0.5.0
