### ISSUE TITLE
Debug in idea

### ISSUE THREAD

**Issue by languanghao** [zinserjan/mocha-webpack#36]
I found the readme shows how to craete sourcemap file for idea, but it does not shows how to debug it.

## Debug tests
1. Clean the **.tmp** folder, you can just delete the folder
2. Run `mocha-webpack --growl`, then you will see it create an '{uuid}-entry.js' file and a folder name with the same uuid
3. Create a **mocha** run/debug configuration, in the *Test Directory* just choose the folder with an uuid name, more info you can find [here](https://www.jetbrains.com/help/pycharm/2016.1/running-mocha-unit-tests.html)
4. Just click **run** or **debug** button

![screenshot 1](https://cloud.githubusercontent.com/assets/3765379/17051915/b19e89fc-502d-11e6-9bf0-f2b17bb63470.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/3765379/17051954/ec300c9e-502d-11e6-9023-c732ffc05c35.png)

**Comment by zinserjan** [comment]
Your suggestion is the old way with just webpack + mocha. It's the same as running webpack before mocha, e.g.
```bash
$ webpack test.js output.js && mocha output.js
```

mocha-webpack allows a much simpler way. You can completely skip the compilation step.

# Debug Tests

1. Create a Testrunner config
![screenshot from 2016-07-26 18 08 53](https://cloud.githubusercontent.com/assets/8046231/17145986/e7a45d56-535c-11e6-832a-c40d48bb500b.png)
  *  replace "Mocha package" path with path of mocha-webpack (should be a (dev-) dependency of your project)
  * set some additional configuration options (mocha-webpack.opts in my case)
  * specify the tests to run
2. make sure that your webpack config contains the following (important for setting breakpoints in src):
  ```javascript
  {
    ...
  
    output: {
        devtoolModuleFilenameTemplate        : '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
      },
  
    ...
  }
  ```

3. also you have to use non-eval devtool in your webpack config, e.g.
  ```javascript
  {
    ...
  
    devtool: '#cheap-module-source-map',
  
    ...
  }
  ```

4. create a `mocha-webpack.opts` to simplify runner configuration
  ```
  --colors
  --require mocha-setup.js
  --webpack-config webpack.config-test.js
  --timeout 0
  --inline-diffs
  src/**/*.test.js
  ```
  *Note*:
  * `src/**/*.test.js` will be overriden by your run configuration
  * if you have to run test files with a specific pattern, you should add the glob option here, e.g. `--glob "*.test.js" `

5. create a `mocha-setup.js` file to get stack traces with original code
    ```javascript
    require('source-map-support').install({
        handleUncaughtExceptions: false,
        environment: 'node',
    });
    ```
6. (optional) set devtool in your webpack config to `#sourcemap` to enable navigation to source code via stack trace
![screenshot from 2016-07-26 18 38 10](https://cloud.githubusercontent.com/assets/8046231/17146869/5e0782f4-5360-11e6-82ff-a5411a82a4ed.png)

7. start your run configuration in debug mode

**Comment by snolangps** [comment]
This look promising, but what are the `[absolute-resource-path]` and `[absolute-resource-path]?[hash]` supposed to be?

**Comment by snolangps** [comment]
It seems that I only needed to add the `devtool: '#inline-cheap-module-source-map',` to my webpack and that fires off breakpoints in WS.
