### ISSUE TITLE
Use os.tmpdir() instead of .tmp

### ISSUE THREAD

**Issue by ericclemmons** [zinserjan/mocha-webpack#37]
(I can send a PR for this if you'd like.)

Until #25 lands (which I think is great, but complicated), rather than `.tmp/`, we could use `require("os").tmpdir()`, which does what it says :)

**Comment by ericclemmons** [comment]
Or, alternatively, give preference to `output.path`, if it exists.

**Comment by zinserjan** [comment]
Hmmm, I think that it's not worth it to invest time on this.

Also, when we move the tmp directory to systems tmp dir, this could lead to problems with webpack's externals config. Node's require algorithm will no longer find node_modules.

**Comment by ericclemmons** [comment]
Makes sense. Thanks!
