### ISSUE TITLE
If outputs are defaulted, the entirety of the object should be defaulted

### ISSUE THREAD

**Issue by ericclemmons** [zinserjan/mocha-webpack#38]
Reading that the `options.outputPath`  and stuff would be ignored even if set, I kept running into the following here:

```js
module.exports = react;
                 ^-- react is undefined
```

This was because I didn't define any `output` options, and some of them (not sure which) are required to work.

**Comment by zinserjan** [comment]
Sorry, I don't understand the issue here. Can you explain a little bit more what's the problem here?

For me it's obviously that your sample code doesn't work, because `react` is never defined in this sample :confused:

**Comment by ericclemmons** [comment]
Sorry I didn't explain it well enough.  If I run into some time I can add the example config.  I'll try to summarize again:

- The documentation mentions that `output.path` is overridden.
- Because of this, I didn't define an `output` object at all in my config.
- This created the odd error above for some reason. :shrug: 
- For it to work, I kept my `output` object with dummy values, and everything worked as intended.

Since this is clearly a rarity & error on my part, I'll close.
