### ISSUE TITLE
Trouble with __dirname

### ISSUE THREAD

**Issue by neelance** [zinserjan/mocha-webpack#39]
My tests have to read (and optionally write) some files relative to the test's `.js` file. For getting the correct path I used `__dirname` before switching to mocha-webpack. Now I'm having a hard time making `__dirname` work. I tried the `node.__dirname` options in the webpack config, but with no success. Do you have any idea on how to solve this? Mocha-webpack works great otherwise, great job!

**Comment by zinserjan** [comment]
Seems that there is no way to get this behavior with webpack without doing something special. Webpack replaces the `__dirname` and `__filename` with constant strings.

Let's do the same. I modified webpack's [NodeStuffPlugin](https://github.com/webpack/webpack/blob/ca8b693c2c17bd06778476381fae23b3b21c0475/lib/NodeStuffPlugin.js) plugin to get the desired effect.

**NodePathReplacePlugin.js**
```javascript
/**
 * Modified NodeStuffPlugin to replace __filename and __dirname with absolute path
 * @see https://github.com/webpack/webpack/blob/ca8b693c2c17bd06778476381fae23b3b21c0475/lib/NodeStuffPlugin.js
 */
function NodePathReplacePlugin() {}
module.exports = NodePathReplacePlugin;
NodePathReplacePlugin.prototype.apply = function(compiler) {

	function setModuleConstant(expressionName, fn) {
		compiler.parser.plugin("expression " + expressionName, function() {
			this.state.current.addVariable(expressionName, JSON.stringify(fn(this.state.module)));
			return true;
		});
	}

	setModuleConstant("__filename", function(module) {
		return module.resource;
	});

	setModuleConstant("__dirname", function(module) {
		return module.context;
	});

};
```

Just require it in your webpack config and add it the plugins sections
**webpack-config.js**
```javascript
var NodePathReplacePlugin = require('./NodePathReplacePlugin');

module.exports = {
....
  plugins: [
    new NodePathReplacePlugin()
  ]
....
}
```

**Comment by neelance** [comment]
Cool, thanks!

**Comment by 0xR** [comment]
This works indeed!

Can this be part of mocha-webpack itself? That way I don't have to add this plugin I don't quite understand to my codebase.
