### ISSUE TITLE
Update peer dependency for `mocha`

### ISSUE THREAD

**Issue by wbobeirne** [zinserjan/mocha-webpack#40]
Looks like mocha updated:  https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#301--2016-08-03

mocha-webpack is currently looking for `mocha@^2.4.5`. For me personally, mocha 3.0.1 is working fine, but this may warrant a major version bump for mocha-webpack as there are breaking changes in it.

**Comment by NameFILIP** [comment]
👍

**Comment by zinserjan** [comment]
Released with 0.6.0.
