### ISSUE TITLE
Does support ES6?

### ISSUE THREAD

**Issue by ozluy** [zinserjan/mocha-webpack#42]
I got following error with React import:
```
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                                                                    ^^^^ ^^
SyntaxError: Unexpected token import
...
```

**Comment by zinserjan** [comment]
Yes and no. 

* Node does't support ES6 modules yet (only with feature flags as far I know)
* Webpack 1 doesn't support ES6 modules
* Webpack 2  brings native support for ES6 modules.

Enabling feature flags to support ES6 modules isn't a option when you want to use webpack 1, cause webpack would not bundle your code properly. 
So, if you want to use ES6 modules with webpack 1 you have to use a loader (e.g. babel with es2015-preset) or use the beta version of webpack 2.

Furthermore you need to precompile all es6 features in your code, that node doesn't understand yet.

To come back to the initial question - Yes, you can use all ES6 features with a ES6 compiler like babel.

**Comment by rosskevin** [comment]
@ozluy if you got this working, I'd be interested to see what you ended up with.

**Comment by ozluy** [comment]
Unfortunately I could not find solution for that @rosskevin. Happy hacking
