### ISSUE TITLE
How to exclude "node_modules"

### ISSUE THREAD

**Issue by zatziky** [zinserjan/mocha-webpack#44]
How can I exclude `node_modules` from the run? 

![mocha-webpack](https://cloud.githubusercontent.com/assets/2794365/18003630/337ed7e8-6b8f-11e6-89a5-15a12435f81c.png)

I thought that `webpack-node-externals` were meant for this task. This is my `webpack.test-config.js`:

```
const nodeExternals = require('webpack-node-externals');
const config = {};

// in order to ignore built-in modules like path, fs, etc.
config.target = 'node';

// in order to ignore all modules in node_modules folder
config.externals = [nodeExternals()];

config.output = {
    // sourcemap support for IntelliJ/Webstorm
    devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
};

// 'cheap-module-source-map' faster than 'source-map'
config.devtool = "source-map";


module.exports = config;
```

I run the tests from `package.json`:

`"test": "mocha-webpack --webpack-config webpack.config-test.js  \"**/test/*.test.js\"",`

**Comment by zinserjan** [comment]
`webpack-node-externals` just marks the modules as external, so these modules are not included into the final js. But they will be evaluated and executed as usual.

Your pattern `\"**/test/*.test.js\"` searches also in node_modules for folders with name `test` and files ending with `.test.js`. Thats your issue, right?

Your project structure leads me to a few questions. Normally, when projects depending on a transpiling step like babel or webpack, they organize their code in a seperate src folder to make code generation into a dist folder easier. 
This and the case that I don't see a normal webpack config leads me to the question if you really need webpack to run your node server. Are you using webpack to compile your project before running your server? Or just wanna test? Then plain mocha would be enough.

**Comment by zatziky** [comment]
@zinserjan, the reasons I want to use `moda-webpack` are 2:

1. to have same environment for FE and BE tests. Since we use `PhpStorm IDE` there is only 1 mocha per running configuration. (I have to choose either `mocha` or `mocha-webpack`. 
2. `mocha --watch` is said to be very CPU intensive. [link](http://randycoulman.com/blog/2016/03/22/testing-with-mocha-and-webpack/) It also will be deprecated. [link](https://github.com/mochajs/mocha/issues/1780)

Anyways, I changed my project structure so that all sources of BE are under one folder and `node_modules` are apart.

I am not sure whether to close the issue. I leave it open and see if this would lead to add an `exlude` alternative...

**Comment by zinserjan** [comment]
When #79 will be released it's possible to pass each directory as an entry to mocha-webpack. 

`"test": "mocha-webpack --webpack-config webpack.config-test.js \"controller/**/test/*.test.js\" \"cron/**/test/*.test.js\"",`
