### ISSUE TITLE
webstorm source maps

### ISSUE THREAD

**Issue by alexey2baranov** [zinserjan/mocha-webpack#49]
Hello! very nice project! 

We use webstorm and read hire https://www.npmjs.com/package/mocha-webpack#sourcemaps we can use source maps for this. We done all as written and get source map file into ./.tmp/mocha-webpack folder but anyway get errors like this into output 

>   10) RemoteModel Zemla.save() "before all" hook:
>      TypeError: Cannot read property '_isLoaded' of undefined
>       at Function.get (.tmp/mocha-webpack/RemoteModel.Test.js:852:23)
>       at Context.<anonymous> (.tmp/mocha-webpack/RemoteModel.Test.js:366:42)
>       at boundThen (.tmp/mocha-webpack/RemoteModel.Test.js:3343:26)
>       at Context.<anonymous> (.tmp/mocha-webpack/RemoteModel.Test.js:365:25)

can we get the stack trace point to out real files from src folder? Thanks!

**Comment by zinserjan** [comment]
Does https://github.com/zinserjan/mocha-webpack/issues/36#issuecomment-235332735 work for you?
