### ISSUE TITLE
Pass CLI options to webpack

### ISSUE THREAD

**Issue by IanVS** [zinserjan/mocha-webpack#60]
As far as I know, there are some webpack cli options like `--progress` which cannot be set in a config file (maybe I'm wrong).  If that's the case, it would be pretty nice if there were a way to pass these options to the underlying webpack.  `--progress` is the one I'd really like, but making it more flexible could be good too.  What do you think, is it possible to do?

**Comment by zinserjan** [comment]
Yep, some kind of progress would be cool.

This brings me to the idea to implement something like [create-react-app](https://github.com/facebookincubator/create-react-app) with auto clearing the console and just display the latest stuff like

- build progress
- build errors
- test reports

and just clear the console between each state change.

**Comment by zinserjan** [comment]
Please have a look at #97.
