### ISSUE TITLE
Weird error messages on failing tests

### ISSUE THREAD

**Issue by kristianmandrup** [zinserjan/mocha-webpack#63]
In my current setup I get some weird errors... any idea?

```
TypeError: (0 , _chai.expect)(...).to.be is not a function
      at Context.that.should (.tmp/mocha-webpack/1125819f4470d55ab4c318bd8d350078/1125819f4470d55ab4c318bd8d350078-output.js:140:3
```

Should I add source maps or not, ie. `--require source-map-support/register`?
I'm using babel 6.18 with webpack 2.1 beta 25.

**Comment by zinserjan** [comment]
Sourcemaps works out of the box with v1.0.0. For configuration have a look at http://zinserjan.github.io/mocha-webpack/docs/installation/webpack-configuration.html#sourcemaps


There were also several sourcemap issues in webpack that were fixed with webpack@2.3.2.
