### ISSUE TITLE
How to avoid jQuery throwing `Error: jQuery requires a window with a document`?

### ISSUE THREAD

**Issue by juancarlosfarah** [zinserjan/mocha-webpack#66]
I just ported my tests to run with `mocha-webpack`, but I'm running into issues with tests that include files with jQuery as a dependency. I have [jsdom](https://github.com/tmpvar/jsdom) creating a fake DOM for my tests, but this doesn't seem to work when compiled by Webpack:

```
  const jsdom = require('jsdom')
  const document = jsdom.jsdom(html, options)
  const window = document.defaultView
  global.document = document
  global.window = window
  window.console = global.console

  // Normally I can access `window` here, but not anymore.
```

I've also included the following in my config file:

```
  plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            ...
        }),
       ...
   ]
```

But that doesn't seem to work either. Is there a recommended way to get jsdom to work with mocha-webpack or somehow provide a window object for jQuery not to error out?

**Comment by sbespalov** [comment]
You can try to do the following:

`window.$ = require('jquery')(window);`

It works for me with similar issue.

**Comment by zinserjan** [comment]
This is quite old, but I tested and documented this here http://zinserjan.github.io/mocha-webpack/docs/guides/jsdom.html

**Comment by ahmed4end** [comment]
still having this problem and no solutions work for it
