### ISSUE TITLE
Pass `--debug` or `--inspect` flags?

### ISSUE THREAD

**Issue by ElliotChong** [zinserjan/mocha-webpack#67]
Is there a way to pass the new [`--inspect`](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.1m0xo5jcu) or legacy `--debug` / `--debug-brk` flags to `mocha-webpack`?

I'd like to be able to debug my tests using the new Chrome Dev Tools integration.

Thanks for `mocha-webpack`- loving it!

**Comment by ElliotChong** [comment]
For the next Googler: Simply execute `mocha-webpack` directly.

Ex:
`node --inspect ./node_modules/mocha-webpack/lib/cli "src/**/*.spec.*"`

**Comment by wangxuepeng** [comment]
Debug Jest unit test following the links works perfect:

`

{

            "type": "node",

            "request": "launch",

            "name": "Jest",

            "protocol": "inspector",

            "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",

            "args": ["--runInBand"],

            "console": "integratedTerminal",

            "sourceMaps": true,

            "stopOnEntry": false

          },

`

but the same approach for mocha does not work:
`

{

            "type": "node",

            "request": "launch",

            "name": "Mocha",

            "protocol": "inspector",

            "program": "${workspaceRoot}/node_modules/mocha-webpack/bin/mocha-webpack",

            "args": [

                "--timeout",

                "999999",

                "--colors",

                "${workspaceFolder}/tests/**/*.spec.*"

            ],

            "console": "integratedTerminal",

            "sourceMaps": true,

            "stopOnEntry": false

          },

`, 


it prompts error below:

_WEBPACK  Failed to compile with 1 error(s)

Error in ./tests/unit/HelloWorld.spec.js

  Module not found: "@/components/HelloWorld.vue" in "/Users/mkw/Dev/vue_mocha/tests/unit"

Waiting for the debugger to disconnect...
Killed: 9_

Looks like it need some webpack configuration?

BTW, I also check link [feat(service): Enable inspector debugging for unit test by mocha](https://github.com/vuejs/vue-cli/pull/2013), it seems the solution, but how to config it in VSCode? 

Thanks.
