### ISSUE TITLE
--watch is not working great with glob

### ISSUE THREAD

**Issue by serut** [zinserjan/mocha-webpack#68]
If I use a conditional glob, it's not working well:  
```
mocha-webpack --webpack-config webpack.test.config.js --timeout 50000 --require source-map-support/register --inline-diffs --watch  "@(tests|web_modules)/**/*.test.js" 
  [MAIN APP] Testing rootReducer
    ✓ should exist
  1 passing (3s)
  0 passing (0ms)
```

But if I remove the conditional case `@(tests|web_modules)` => `web_modules`, it works !
```
mocha-webpack --webpack-config webpack.test.config.js --timeout 50000 --require source-map-support/register --inline-diffs --watch  "web_modules/**/*.test.js" 
  [ADMIN APP] Testing projects actions
    GET /projects calls
      ✓ should leverage a request action on fetch request
      ✓ should leverage a success action on fetch success
      ✓ should leverage a failure action on fetch failure
[...]
  48 passing (6s)
  5 pending

```

**Comment by zinserjan** [comment]
@serut Does this problem only occur in watch or even in "single-run" mode?

My expectation is, that it happens also without watch.

**Comment by serut** [comment]
I still don't get it @zinserjan 

### Not watching
```
mocha-webpack --webpack-config webpack.test.config.js "@(tests|web_modules)/**/*.test.js{,x}" --recursive
  2 passing (52ms)
```

```
mocha-webpack --webpack-config webpack.test.config.js "**/@(tests|web_modules)/**/*.test.js{,x}" --recursive
  149 passing (730ms)
  4 pending
```

### Watching
```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "**/{tests,web_modules}/**/*.test.js{,x}" --recursive --watch
  2 passing (4s)
  0 passing (2ms)
```

```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "**/@(tests|web_modules)/**/*.test.js{,x}" --recursive --watch
  2 passing (4s)
  0 passing (3ms)
```

```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "web_modules/**/*.test.js{,x}" --recursive --require source-map-support/register --inline-diffs --watch --reporter nyan
  147 passing (2s)
  4 pending
```

```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "**/web_modules/**/*.test.js{,x}" --recursive --watch

  0 passing (2ms)
  0 passing (1ms)

```

**Comment by zinserjan** [comment]
Thanks. The glob matching algorithm is the same for both. The only difference is that the watch mode use also another plugin to detect which tests needs to run. Seems that there is bug in this plugin. 

A few days ago I have been started to do a complete rewrite. Watch mode is now identical to the single run mode. I would appreciate it if you can test this again against the current master.

Here are some instructions to get this working:

1. delete mocha-webpack from node_modules (no uninstall to keep files in .bin folder intact)
2. git clone into node_modules
3. cd mocha-webpack
4. npm install
5. npm run build
6. run your tests again

**Comment by serut** [comment]
Thanks it works great !!
```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "**/@(tests|web_modules)/**/*.test.js{,x}" --recursive --watch
  159 passing (2s)
  4 pending
```


```
mocha-webpack --timeout 5000 --webpack-config webpack.test.config.js "**/{tests,web_modules}/**/*.test.js{,x}" --recursive --watch
  159 passing (3s)
  4 pending
```

**Comment by zinserjan** [comment]
Yay! Sounds great. I'll try to complete the remaining coding tasks for 1.0.0 in the next days and make a prerelease. 

Can you also test the `in-memory` branch from #83 with your test suite?

**Comment by serut** [comment]
How can I test the`in-memory` improvement ? Just in terms of speed ?

**Comment by serut** [comment]
```
git fetch in-memory
git checkout in-memory
npm run test:mocha
  159 passing (358ms)
  4 pending

```

**Comment by zinserjan** [comment]
>How can I test the in-memory improvement ?

Test should run and no files are written to .tmp. That's all :)

>Just in terms of speed ?

Theoretically yes, but I didn't notice any speed improvements so far.

**Comment by zinserjan** [comment]
Did you run `npm install` & `npm run build` again?

**Comment by serut** [comment]
Nop. Good catch

**Comment by serut** [comment]
I don't have the `.tmp` folder but I have two new error that I didn't had previously.

```
157 passing (580ms)
  4 pending
  2 failing

  1) [COMMON] Testing i18n actions Test actions creation for internationalization language change:
     Error: Cannot find module './1.bundle.js'
      at Function._resolveFilename (node_modules/mocha-webpack/lib/webpack/util/registerRequireHook.js:36:34)
      at require (internal/module.js:20:19)
      at Function.requireEnsure [as e] (.tmp/mocha-webpack/webpack/bootstrap e12f69137d35a6eb37ff:39:1)
[ my code]

  2) [COMMON] Testing i18n actions Test fallback en-US --> en:
     Error: Cannot find module './1.bundle.js'
      at Function._resolveFilename (node_modules/mocha-webpack/lib/webpack/util/registerRequireHook.js:36:34)
      at require (internal/module.js:20:19)
      at Function.requireEnsure [as e] (.tmp/mocha-webpack/webpack/bootstrap e12f69137d35a6eb37ff:39:1)
[ my code]
```

I reswitched to master, npm install & npm run build, and my tests are fine
```
  159 passing (388ms)
  4 pending
```

**Comment by zinserjan** [comment]
Are you using code splitting like require.ensure?

**Comment by serut** [comment]
Yes we use code splitting with `require.ensure` but not on that algorithm

**Comment by zinserjan** [comment]
So sometimes it works with `require.ensure` and sometimes not?

Anyway, can you create a minimal failing example? That would be so awesome and helps me alot :)

**Comment by serut** [comment]
> So sometimes it works with require.ensure and sometimes not?

It works when the path is static, like 
```
require.ensure([], (require) => {
      const ProjectFormContainer = require('./containers/FormContainer')
      cb(null, {
        content: FormContainer.default,
      })
})
```
but not when it's computed.
