### ISSUE TITLE
CommonsChunkPlugin

### ISSUE THREAD

**Issue by jjhuff** [zinserjan/mocha-webpack#84]
Super handy, project, thanks!!

I noticed that when I include CommonsChunkPlugin in my webpack plugins, mocha-webpack doesn't find any tests.

Not a huge issue for me, but it'd be nice if it worked since I'd be able to keep my configs a little cleaner.

**Comment by zinserjan** [comment]
Can you give me an example? Didn't tried this yet, but I'll look into it.

**Comment by jjhuff** [comment]
I'll need some more time to setup a working mini-example, but here's an excerpt from my webpack config.
```
plugins: [
    new webpack.optimize.CommonsChunkPlugin('lib'),
    new webpack.optimize.CommonsChunkPlugin({
      minChunks: 2,
      children: true,
    }),
    // This chunk contains only a small loader and the chunk manifest.
    // It'll be inlined into index.html
    new webpack.optimize.CommonsChunkPlugin({
      name: 'inline',
      filename: '../../src/motion.social/frontend/build/inline.js',
      minChunks: Infinity,
    }),
]
```
With this, mocha doesn't find any tests ("0 passing").

If I set
```
plugins: []
```
mocha finds and runs my tests.

Let me know if you want me to setup a full example.

**Comment by zinserjan** [comment]
> Let me know if you want me to setup a full example.

That would be so awesome when you can find the time to do this. Thank you for your effort :)

**Comment by zinserjan** [comment]
CommonsChunkPlugin is incompatible with `target: 'node'` (webpack/webpack#1518).

The only thing we can do is to warn the user when the CommonsChunkPlugin is used. I added that issue to the to-do list in #70.

**Comment by jjhuff** [comment]
Ahh! That'd do it. Thanks!

**Comment by mattkahl** [comment]
FWIW, this was closed but as far as I can tell the to-do referenced in #70 was never completed.
