### ISSUE TITLE
Devtool eval

### ISSUE THREAD

**Issue by alexanderchr** [zinserjan/mocha-webpack#9]
First, thanks a lot for creating this.

~~I spent some time tonight trying to get it running in webpack 2. Without watch it worked out of the box, with, it crashed. I don't know the details but it seems as if webpack has changed how evaled modules are handled as the built files contained:~~

With devtool eval:

`eval("[...] __webpackManifest__ = ["file1", "file2"] [...]")`

Which obviously does not work. But, by escaping in https://github.com/zinserjan/mocha-webpack/blob/master/src/webpack/InjectChangedFilesPlugin.js#L88

I.e. `const changedFiles = JSON.stringify(this.hotFiles.concat(this.failedFiles)).replace(/"/g, '\\"');`

Watch mode works flawlessly.

**Comment by zinserjan** [comment]
Thanks for trying webpack 2 with this lib.

Encoding strings to support webpack 2 sounds strange for me. So I played a bit with webpack 1 & 2...

I never got the eval statement in the bundle with my default config. But with `eval` as devtool mocha-webpack started to fail in watch mode.

Error:
```
SyntaxError: Unexpected token /
```

The reason for the failing watch mode is that InjectChangedFilesPlugin is only applied in watch mode.

Can you verify that it fails only with `eval` as devtool in combination with watch mode?

**Comment by alexanderchr** [comment]
You are correct - it only happens with `devtool: eval`. My fault for assuming it was connected to webpack 2.

If you don't mind i wont close this yet as i think incompatibility with `devtool: eval` is a major enough to problem to warrant at least looking at it. Cleverly replacing and escaping `"` seems to work but does not feel very sustainable.

**Comment by thiagoa** [comment]
Hello,

I just verified this is a syntax error in the code replaced by `InjectChangedFilesPlugin `, it's not related with devtools eval and it also happens in Node CLI. I've opened a pull request with a sample app (which uses webpack 1) in which the failure can be verified. More details in the description:

https://github.com/zinserjan/mocha-webpack/pull/17

**Comment by talyssonoc** [comment]
As @thiagoa stated, it's not directly related to Webpack 2, looks like it happens because the code generated to be evaluated uses double-quotes, and when the following is run: `eval("[...] __webpackManifest__ = ["file1", "file2"] [...]")`, it fails.

An alternative solution for his PR (not sure if it's better or not) would be generate the array not using `JSON.stringify` (which is the reason for the double-quotes), but with `'[' + replacement join(', ') + ']'`.

**Comment by zinserjan** [comment]
Fixed with v0.4.0
